##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## Makefile
##

all:
	make -C my_csfml
	make -C my_lib_c

clean:
	make clean -C my_csfml
	make clean -C my_lib_c

fclean: clean
	make fclean -C my_csfml
	make fclean -C my_lib_c

re: fclean all

.PHONY: all re fclean clean
