
all:
	@make -C Ncurses/
	@make -C sfml/

clean:
	@make clean -C Ncurses/
	@make clean -C sfml/

fclean:
	@make fclean -C Ncurses/
	@make fclean -C sfml/

re:
	@make re -C Ncurses/
	@make re -C sfml/

.PHONY: all clean fclean re