##
## EPITECH PROJECT, 2019
## SEC_crypto_2019
## File description:
## Makefile
##


all:
	cp challenge01.py challenge01
	cp challenge02.py challenge02
	cp challenge03.py challenge03
	cp challenge04.py challenge04
	cp challenge05.py challenge05
	cp challenge06.py challenge06
	cp challenge07.py challenge07
	cp challenge08.py challenge08
	cp challenge09.py challenge09
	cp challenge10.py challenge10
	cp challenge11.py challenge11
	cp challenge12.py challenge12
	cp challenge13.py challenge13
	cp challenge14.py challenge14

clean:

fclean: clean
	rm -rf challenge01
	rm -rf challenge02
	rm -rf challenge03
	rm -rf challenge04
	rm -rf challenge05
	rm -rf challenge06
	rm -rf challenge07
	rm -rf challenge08
	rm -rf challenge09
	rm -rf challenge10
	rm -rf challenge11
	rm -rf challenge12
	rm -rf challenge13
	rm -rf challenge14

re: fclean all

.PHONY: all fclean clean re