all:
	@make -C justatest/
	@make -C snake/
	@make -C qix/

clean:
	@make clean -C justatest/
	@make clean -C snake/
	@make clean -C qix/

fclean:
	@make fclean -C justatest/
	@make fclean -C snake/
	@make fclean -C qix/

re:
	@make re -C justatest/
	@make re -C snake/
	@make re -C qix/

.PHONY: all clean fclean re
