all:
	cp pbrain-gomoku.py pbrain-gomoku-ai
	chmod +x pbrain-gomoku-ai

clean:
	echo "nothing do to."

fclean: clean
	rm -rf pbrain-gomoku

exe:
	sh bonus/create_exe.sh pbrain-gomoku.py

.PHONY: all clean fclean re