##
## EPITECH PROJECT, 2017
## 
## File description:
## 
##

all:
	make -C my_csfml
	make -C my_printf

clean:
	make clean -C my_csfml
	make clean -C my_printf

fclean: clean
	make fclean -C my_csfml
	make fclean -C my_printf

re: fclean all

.PHONY: all fclean clean re
